version: '3'
services:
    database:
        container_name: postgres_jn2
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=jn2_test
        ports:
            - '5432:5432'
        volumes:
            - ./docker/postgres-data:/var/lib/postgresql/data          
volumes:
    docker:
